title: Tacos und Limetten
url: https://tacosundlimetten.de

### download_url: is needed, if and only if audio files are hosted in a different location, it is the path of the directory where the audio files are stored
# download_url: "http://your.fancy.hosting/episodes"
subtitle: Ein Mexiko-Podcast
description: Florian Posdziech spricht mit Deutschen und Deutschsprachigen in Mexiko über das Land und das Leben hier.
author: Florian Posdziech

### author_url: This is the URL of a site owned by the author (see https://jsonfeed.org/version/1)
author_url: "https://flowfx.de/"

email: tacosundlimetten@flowfx.de
keywords: [octopod, podcast, magic]
itunes_categories: [Society & Culture, Places & Travel]
episodes_per_feed_page: 100

player_theme: default # default | "default-dark" | legacy | minimal | republica

### Date can be localized via date_de.rb plugin, you don't need to change this
date_format: ordinal

### Rsync Deploy config: Be sure your public key is listed in your server's ~/.ssh/authorized_keys file
ssh_host: user@host.org
ssh_port: 22
document_root: /path/to/your/htdocs/
rsync_delete: true

### Twiter config, optional
# twitter_nick: my_twitter_handle # Twitter will not be used unless this is set

language: de
explicit: "no" # "yes" | "no" | clean

### License Config, you really should configure this
license: CC BY 4.0
license_url: https://creativecommons.org/licenses/by/4.0/
license_image_url: https://i.creativecommons.org/l/by/4.0/88x31.png

### Feed links, optional
itunes_url: https://podcasts.apple.com/podcast/id1126484634

theme: jekyll-bootflat

plugins:
  - jekyll-octopod
